### ISSUE TITLE
lint

### ISSUE THREAD

**Issue by philippemiron** [Cloud-Drift/clouddrift#97]
Ok, I was really confused by this linting error.

The files are fine, but there is a circular import... See for example when you run:

```
$ black haversine.py dataformat.py
All done! ✨ 🍰 ✨
2 files left unchanged.
(research) pmiron@m2air ~/Downloads/clouddrift/clouddrift
$ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/multiprocessing/__init__.py", line 16, in <module>
    from . import context
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/multiprocessing/context.py", line 6, in <module>
    from . import reduction
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/multiprocessing/reduction.py", line 16, in <module>
    import socket
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/socket.py", line 54, in <module>
    import os, sys, io, selectors
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/selectors.py", line 12, in <module>
    import select
  File "/Users/pmiron/Downloads/clouddrift/clouddrift/select.py", line 1, in <module>
    import awkward as ak
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/site-packages/awkward/__init__.py", line 7, in <module>
    import awkward._nplikes
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/site-packages/awkward/_nplikes.py", line 7, in <module>
    import numpy
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/site-packages/numpy/core/__init__.py", line 100, in <module>
    from . import _add_newdocs_scalars
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/site-packages/numpy/core/_add_newdocs_scalars.py", line 9, in <module>
    import platform
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/platform.py", line 119, in <module>
    import subprocess
  File "/Users/pmiron/micromamba/envs/research/lib/python3.10/subprocess.py", line 223, in <module>
    _PopenSelector = selectors.SelectSelector
AttributeError: partially initialized module 'selectors' has no attribute 'SelectSelector' (most likely due to a circular import)
```

Long story short, the issue is with the *name* of the module `select.py`. If you rename it to anything else, it works. So my guess is that `black` is importing another module call `select.py` (https://docs.python.org/3/library/select.html).

The solution is to change the name of the `select.py` module, but to be honest I don't have any good suggestions.

**Comment by milancurcic** [comment]
I can't reproduce this locally. Black version? Mine is:

```
black, 22.8.0 (compiled: yes)
Python (CPython) 3.10.6
```

**Comment by philippemiron** [comment]
$ black --version
black, 22.12.0 (compiled: no)
Python (CPython) 3.10.8

**Comment by milancurcic** [comment]
I tried a newer version and that allowed me to format analysis.py to make linter happy in #100.

```
black, 23.1.0 (compiled: yes)
Python (CPython) 3.11.0rc1
```

I still can't reproduce this.

Does the error remain if you run it from one directory up? i.e.:

```
black clouddrift/analysis.py clouddrift/haversine.py
```

If not, our "solution" may be to simply not run black in the same directory as select.py.

**Comment by philippemiron** [comment]
It works from one directory up. But I think VSCode runs it automatically at the file level automatically when I save. I guess the _solution_ is find for now.
